apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codetry
    tier: backend
  name: codetry-deployment
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: php
          resources:
            limits:
              cpu: 400m
              memory: 900Mi
            requests:
              cpu: 10m
              memory: 300Mi
        - name: nginx
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 63Mi
