apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codetry-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
      host: codetry-staging.kube.drom.ru
