apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codetry-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /mock-server(/|$)(.*)
      host: codetry-staging.kube-dev.drom.ru
