cache:
  paths:
    - vendor/
  key: "${CI_PROJECT_PATH_SLUG}"

stages:
  - build

variables:
  BACKEND_MOCK_SERVER_IMAGE_NAME_PHP_LATEST: codetry/backend-mock-server-php:latest
  BACKEND_MOCK_SERVER_IMAGE_NAME_PHP_TAGGED: codetry/backend-mock-server-php:${CI_PIPELINE_IID}-${CI_COMMIT_REF_NAME}

build_backend_mock_server_image:
  tags:
    - fines
  stage: build
  image: "$DOCKER_REGISTRY/library/gitlab-runner-image:with-git"
  only:
    refs:
      - merge_requests
      - master
    changes:
      - docker/mock-server/*
      - src/backend-mock-server/*
  script:
    - echo "$DOCKER_PASS" | docker login "$DOCKER_REGISTRY" -u $DOCKER_USER --password-stdin
    - docker pull $DOCKER_REGISTRY/$BACKEND_MOCK_SERVER_IMAGE_NAME_PHP_LATEST
    - docker build -t $DOCKER_REGISTRY/$BACKEND_MOCK_SERVER_IMAGE_NAME_PHP_TAGGED -f docker/mock-server/Dockerfile .
    - docker push $DOCKER_REGISTRY/$BACKEND_MOCK_SERVER_IMAGE_NAME_PHP_TAGGED