version: '2.2'
services:
  nginx:
    container_name: $APP_COMPOSE_PROJECT_NAME-nginx
    build: docker/nginx
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/var/log/nginx:/var/log/nginx
    depends_on:
      - php-hub
      - php-fpm-53
      - php-fpm-54
      - php-fpm-55
      - php-fpm-56
      - php-fpm-70
      - php-fpm-71
      - php-fpm-72
      - php-fpm-73
      - php-fpm-74
      - php-fpm-80
    restart: always
    ports:
      - 80:80
    networks:
      outside-network:
        aliases:
          - $APP_COMPOSE_PROJECT_NAME
      backend-network:
  php-hub:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-hub
    build: docker/php-hub
    user: $APP_DOCKER_UID:$APP_DOCKER_GID
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/backend:/var/www
      - ./docker/php-hub/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-hub/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-80:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-80
    build: docker/php-fpm-80
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-80/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-80/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-74:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-74
    build: docker/php-fpm-74
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-74/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-74/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-73:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-73
    build: docker/php-fpm-73
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-73/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-73/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-72:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-72
    build: docker/php-fpm-72
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-72/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-72/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-71:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-71
    build: docker/php-fpm-71
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-71/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-71/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-70:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-70
    build: docker/php-fpm-70
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-70/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-70/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-56:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-56
    build: docker/php-fpm-56
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-56/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-56/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-55:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-55
    build: docker/php-fpm-55
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-55/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-55/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-54:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-54
    build: docker/php-fpm-54
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-54/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-54/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  php-fpm-53:
    container_name: $APP_COMPOSE_PROJECT_NAME-php-fpm-53
    build: docker/php-fpm-53
    volumes:
      - ./src/backend-php-sandbox:/var/www
      - ./docker/php-fpm-53/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm-53/php.ini:/usr/local/etc/php/conf.d/00-php.ini
    working_dir: /var/www/
    restart: always
    networks:
      - backend-network
  nodejs:
    container_name: $APP_COMPOSE_PROJECT_NAME-nodejs-builder
    image: eldarco/code-try:front-latest
    working_dir: /home/node
    env_file: .env
    volumes:
      - ./src/backend/public/frontend:/home/dist
      - ./src/frontend/prod-entrypoint.sh:/entripont.sh
    command: sleep 3600
    networks:
      - backend-network
  db:
    container_name: $APP_COMPOSE_PROJECT_NAME-db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
    restart: always
    environment:
      - MYSQL_DATABASE=${APP_DB_DATABASE}
      - MYSQL_USER=${APP_DB_USER}
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${APP_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${APP_DB_USER}", "-p${APP_DB_PASSWORD}"]
      timeout: 20s
      retries: 10
    networks:
      - backend-network
    volumes:
      - ./database:/var/lib/mysql
networks:
  backend-network:
  outside-network:
    external:
      name: $APP_SERVICE_NETWORK_NAME
