apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  config : |
    server {
      server_name _;

      listen *:80 default_server;
      error_log  /var/log/nginx/error.log;
      access_log off;
      root /usr/src/myapp;
      charset utf-8;

      location / {
        rewrite ^ /index.php last;
      }

      location ~ \.(js|htc|ico|gif|jpg|png|css)$ {
      }

      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/public$fastcgi_script_name;
        include fastcgi_params;
      }
    }
