apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: fines
    tier: backend
spec:
  selector:
    app: fines
    tier: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
